"""This file defines the core types used in the Markus Autotesting system."""

from __future__ import annotations
from functools import reduce
from typing import Annotated, Any, Optional, Union

from msgspec import Meta, Struct


class _AutotestSettings(Struct, kw_only=True):
    """The main test settings data type."""

    testers: Annotated[list, Meta(title="Testers", min_length=1)]
    """The list of testers configured for these settings."""

    _user: Optional[str] = None
    """The user who last updated the test settings."""

    _last_access: Optional[int] = None
    """The last time the test settings were updated."""

    _files: Optional[str] = None
    """A list of test files associated with these settings."""

    _env_status: Optional[str] = None
    """The status of the test environment creation for these settings."""

    _error: Optional[str] = None
    """An error message, populated when creating a test environment fails."""


def create_autotest_settings_class(tester_classes: list[type]) -> type[Struct]:
    """Dynamically create an AutotestSettings data type.

    This uses _AutotestSettings as the base class, replacing the `testers` annotation
    with a union of the provided tester_classes.
    """
    return type(
        "AutotestSettings",
        (_AutotestSettings,),
        {
            "__annotations__": {
                "testers": Annotated[
                    list[reduce(lambda a, b: Union[a, b], tester_classes)],
                    Meta(title="Testers", min_length=1),
                ]
            }
        },
    )


class BaseTesterSettings(
    Struct,
    kw_only=True,
    tag_field="tester_type",
    tag=lambda x: x.removesuffix("TesterSettings").lower(),
):
    """The settings for an individual tester.

    This is a tagged union of various testers, using `tester_type` as the discriminator field.
    """

    test_data: Optional[Any] = None
    """The settings for the tester."""

    @property
    def tester_type(self) -> str:
        return self.__class__.__name__.removesuffix("TesterSettings").lower()

    _env: Optional[dict[str, Any]] = None
    """Environment variables to pass to the tester."""


class BaseTestData(
    Struct,
    kw_only=True,
):
    """Base class for all `test_data` fields.

    This is subclassed to specify tester-specific `test_data` settings.
    """

    category: Annotated[
        list[
            Annotated[
                str,
                Meta(extra_json_schema={"$ref": "#/definitions/test_data_categories"}),
            ]
        ],
        Meta(title="Category", extra_json_schema={"uniqueItems": True}),
    ]

    script_files: Annotated[
        list[AutotestFile],
        Meta(title="Test files", min_length=1, extra_json_schema={"uniqueItems": True}),
    ]
    """The file(s) that contain the tests to execute."""

    timeout: Annotated[int, Meta(title="Timeout")] = 30
    """The timeout in seconds for this test group."""

    feedback_file_names: Annotated[list[str], Meta(title="Feedback files")]
    """A list of file paths generated by executing this test group."""

    extra_info: Annotated[
        Any, Meta(extra_json_schema={"$ref": "#/definitions/extra_group_data"})
    ] = {}
    """Additional information for this test group."""


AutotestFile = Annotated[
    str, Meta(extra_json_schema={"$ref": "#/definitions/files_list"})
]
"""A placeholder in the JSON schema representing one of the files provided to the autotesting environment."""
